# choco install amazon-music
# choco install anyvideoconverter
# choco install audacity
# choco install blender
# choco install ffmpeg-full
# choco install flac
# choco install gimp
# choco install handbrake
# choco install imagemagick
# choco install irfanview
# choco install itunes
# choco install obs-studio
# choco install paint.net
# choco install plex
# choco install png2ico
# choco install reaper
# choco install screentogif
# choco install snagit
# choco install spotify
# choco install streamdeck
# choco install streamlabs-obs
# choco install tinymediamanager
# choco install vlc