# choco install autohotkey
# choco install autoit
# choco install cmake
# choco install go
# choco install gradle
# choco install groovy
# choco install gulp-cli
# choco install jdk8
# choco install jenkins
# choco install less
# choco install lua
# choco install make
# choco install microsoft-r-open
# choco install microsoft-visual-cpp-build-tools
# choco install mono
# choco install nasm
# choco install nodejs
# choco install numpy
# choco install nvm
# choco install openjdk
# choco install php
# choco install phpstorm
# choco install powerautomatedesktop
# choco install pydev
# choco install python2
# choco install python3
# choco install pywin32
# choco install r
# choco install rabbitmq
# choco install ruby
# choco install rust
# choco install sass
# choco install terraform
# choco install terraform-docs
# choco install typescript
# choco install vb5runtime
# choco install yarn